### ISSUE TITLE
Add AutoScaling Support

### ISSUE THREAD

**Issue by hspencer77** [lambda-my-aws/ecs_composex#122]
### Feature Request

Feature request to add autoscaling support for ECS workloads deployed.  Autoscaling support should be added for the following:
- CPU utilization - ([ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#available_cloudwatch_metrics))
- Memory utilization - ([ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#available_cloudwatch_metrics))
- Request Count Per Target ([ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html))
- Target Response Time ([ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html))
- HTTPCode_Target_3XX_Count, HTTPCode_Target_4XX_Count, HTTPCode_Target_5XX_Count ([ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html))

Some additional ones that would be helpful:
- ApproximateNumberOfMessagesVisible ([SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html))

### Use Cases

- Autoscale ECS workloads based upon CPU/Memory metrics
- Autoscale ECS workloads based upon ALB metrics (this is helpful if a given workload deployed on ECS has a certain performance characteristic that would require a faster scaling out response instead of waiting for CPU/Memory on ECS to get to a specific level)
- Autoscale on SQS queue when X number of messages are visible (this would allow a ratio mapping of the number of ECS tasks per number of messages)

**Comment by JohnPreston** [comment]
Done for CPU/RAM.
Working on SQS based scaling so going to work on a merge of the two features.

**Comment by JohnPreston** [comment]
@hspencer77 SQS based step scaling is done. Further investigation and testing to be done but technically works.

**Comment by JohnPreston** [comment]
To do: LB based scaling.
