### ISSUE TITLE
Custom DependsOn.Condition for sidecar containers

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#161]
**Is your feature request related to a problem? Please describe.**
I'd like to use a sidecar container to run my migrations when my service starts. This container will run and then exit. My main container should not start until this has finished. If it exits with a failure, the main service container should not start at all.

**Describe the solution you'd like**
Currently additional containers using `ecs.task.family` are hardcoded to a `DependsOn.Condition` of `START` or `HEALTHY`. I would like to be able to override this to `SUCCESS`

https://github.com/lambda-my-aws/ecs_composex/blob/f6021ec64ca253093985c428abf08d1a92f04d48/ecs_composex/ecs/ecs_service.py#L158

**Comment by JohnPreston** [comment]
Suggested solution:

```
ecs.depends.condition: START|SUCCESS|COMPLETE|HEALTHY
```

note that if `healthcheck` is set, the condition will be set to HEALTHY automatically.

**Comment by jackqu7** [comment]
Would this work if you had > 2 containers? (with different conditions required)

**Comment by JohnPreston** [comment]
This sets the container's own condition. I am not sure that one service would have a different condition even split to 2 families
