### ISSUE TITLE
Multiple families for service

### ISSUE THREAD

**Issue by jackqu7** [lambda-my-aws/ecs_composex#162]
**Is your feature request related to a problem? Please describe.**
I'd like to use a sidecar container to run my migrations when my services start. Multiple services all require the same migration container. Currently I need to have duplicate service definitions because a service can only be in one `ecs.task.family`.

**Describe the solution you'd like**
I would like to specify more than one family a service belongs to.

**Comment by JohnPreston** [comment]
Implemented in the current root branch. Aimed to be released with 0.9.0

**Comment by JohnPreston** [comment]
Released as part of 0.8.6
