### ISSUE TITLE
Enable alerts for resource metrics 

### ISSUE THREAD

**Issue by MuyiwaOla** [lambda-my-aws/ecs_composex#195]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I would like a way to trigger alerts when a metric has gone into a state of alarm.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JohnPreston** [comment]
@MuyiwaOla  thanks for raising the PR.
So you want to be able to define alerts you already have created or create new alerts and then do something?
Are these alerts aimed at changing the way the services in ECS behave ? Or for x-rds, you would like for aurora DB to implement scaling?
Thank you :pray:

**Comment by MuyiwaOla** [comment]
I would aim these changes at x-rds , scaling is not required for my use case at this stage.

**Comment by JohnPreston** [comment]
Will be part of a bigger `x-alarm` or `x-monitoring`
