### ISSUE TITLE
AWS DocumentDB support

### ISSUE THREAD

**Issue by miczaw** [lambda-my-aws/ecs_composex#222]
**Is your feature request related to a problem? Please describe.**
**As an** engineer
**I want to deploy** DocumentDB instance
**And** provide necessary configurations such as resources, permissions, number of instances etc.

**Comment by JohnPreston** [comment]
Supporting documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbclusterparametergroup.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbinstance.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbsubnetgroup.html

For username/password, similar to RDS,

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html

@miczaw any idea how you want to define the properties yet?
