### ISSUE TITLE
x-acm public zone ID coming from x-dns, this needs clearer identification or slight rework of the app

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#241]
**Is your feature request related to a problem? Please describe.**
I tried to use x-acm but the Zone ID would not be taken in account because I did not specify x-dns/PublicZone/Use

**Describe the solution you'd like**
Improve the docs or in absence of x-dns use the value submitter in properties

**Comment by pramodvkrishna** [comment]
Also please correct the typo(change lower case 'use' to 'Use') in example section of page https://docs.ecs-composex.lambda-my-aws.io/syntax/composex/dns.html#dns-reference-syntax

**Comment by JohnPreston** [comment]
Fixed typo
Will adapt the code to take in the parameter and come up with a Macro Setting for validations
