### ISSUE TITLE
Improve JsonKeys usability

### ISSUE THREAD

**Issue by JohnPreston** [lambda-my-aws/ecs_composex#320]
## Is your feature request related to a problem? Please describe.
* As a developer, at first it was not quite clear what the `Key` and the `Name` were for and so it would be helpful to rename
`Key` to `SecretKey` and `Name` to `VarName`.
* If I have a key that is already in an acceptable format to be an Environment Variable, defining `SecretKey` alone should mean I want my `VarName` to use the same name
* It could be useful to introduce a `Transform` action, with multiple options (title, capitalize, java_override) which would automatically transform the `SecretKey` to a different `VarName`

**Describe the solution you'd like**
```
x-secrets:
  secretA:
    name: ABCD
    x-secrets:
      Name: /path/to/secret/in/secretsmanager
      JsonKeys:
       - SecretKey: toto
       - VarName: TOTO
```

## Suggested transforms

* java_override -> capitalizer (upper) all letters and replaces `.` with `_`
`property.name` becomes `PROPERTY_NAME`

* upper
`some.example` becomes `SOME.EXAMPLE`

* title
`some.example` becomes `Some.Example`

**Comment by LinaPupeik** [comment]
Perfect improvement. This improvement gives more flexibility to describe and add secrets that are needed.  Will definitely use it to improve the code.
