### ISSUE TITLE
Trying to use RDS, I am getting error from CFN

### ISSUE THREAD

**Issue by LinaPupeik** [lambda-my-aws/ecs_composex#342]
**Describe the bug**
the error from CFN is this:
No default subnet detected in VPC. Please contact AWS Support to recreate default Subnets. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidSubnet; Request ID: 0c3593b5-8dd6-4190-bddc-e345f73c7442; Proxy: null)

**To Reproduce**
1. How you installed ECS ComposeX'...' --> buildspeck.yml file (using the codepipeline AWS). Used ComposeX 0.10.0
2. How you are executing it ? : As a CLI tool, as a library, in lambda? --> As CLI

**Expected behavior**
--> RDS will be deployed in Storage subnet/'s as it was in the earlier version.

**Comment by JohnPreston** [comment]
Thanks @LinaPupeik for reporting this.
0.10.1 will come out soon with the fix

**Comment by JohnPreston** [comment]
Tested DocDB changes and all good with deployment.
@LinaPupeik  can you confirm we are all good for you with this?

**Comment by LinaPupeik** [comment]
Yes it works with Aurora DB (tested on aurora-postgresql:11.7)
