### ISSUE TITLE
Resulting CFN template shows mismatch in ALB HealthCheckPath

### ISSUE THREAD

**Issue by krishin-js** [lambda-my-aws/ecs_composex#413]
Description of the error:
Given I have an ALB in my yaml configuration file
When I have specified a health-check of a service with a path /swagger-ui/index.html
(healthcheck: 8080:HTTP:7:2:15:5:/swagger-ui/index.html:200)
Then the resulting CFN template only reflects **/index.html** in the HealthCheckPath.

Expected output:
Given I have an ALB in my yaml configuration file
When I have specified a health-check of a service with a path /swagger-ui/index.html
(healthcheck: 8080:HTTP:7:2:15:5:/swagger-ui/index.html:200)
Then the resulting CFN template should reflect **/swagger-ui/index.html** in the HealthCheckPath.

**Comment by JohnPreston** [comment]
Hi @krishin-js 
Will have a look at that, seems like a regexp issue. Sorry for the inconvenience
