### ISSUE TITLE
Enable AppMesh Support

### ISSUE THREAD

**Issue by hspencer77** [lambda-my-aws/ecs_composex#57]
[AWS AppMesh integration with ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/appmesh-getting-started.html) enables the following:
- better end-to-end visibility for ECS services
- additional network control and monitoring

### Prerequisites 
- [ECS Service Discovery](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html) needs to be enabled

**Comment by JohnPreston** [comment]
Implemented an working by https://github.com/lambda-my-aws/ecs_composex/pull/96
Slight networking rework to do.
